# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 929591d476e8cc668859ffed1df19b6a58bf77fe17f9858ff40d3f012a839a11caa53839e0a8fd1cfaccc957cc7e4e6adf029b6f5819f0966c3c3418516daff2

test:
  secret_key_base: 61037ebfd1b200f1171714f10aef67f2fd03493fb4915f8a0d63581b23d9eb3268981fd4f4277685c274e5f7323a740d1bbf07ac457e15105e02ecd09b8d3ad7
  google_maps_api_key: AIzaSyBFzJkpEMTm40_GViQsiQ9uHIecbhI4yDA

# Do not keep production secrets in the repository,
# instead read values from the environment.#AIzaSyCfTGweoOHBu3ooYtXFgO0kVw_Htws4sO8 #
production:
  secret_key_base: 'not needed, but rails-api will complain otherwise' #https://github.com/rails-api/rails-api/issues/72
